wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1677484196.540558
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.13.10
      8:
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.02
